### ISSUE TITLE
Contact information

### ISSUE THREAD

**Issue by Transflux24** [WulfMarius/ModComponent#1]
Hello, I'm trying to work on making some mods for The Long Dark and I'm not really sure how to find contact information on here. I was wondering what tools you used besides Visual Studio, like where did you get the model for the binoculars? Anyways, if you have a way to better contact you I can't find it lol.

**Comment by WulfMarius** [comment]
* On twitter: https://twitter.com/WulfMarius
* On reddit: https://www.reddit.com/user/WulfMarius
