### ISSUE TITLE
getting an error from latest modcomponent

### ISSUE THREAD

**Issue by ShabbirSS** [WulfMarius/ModComponent#4]
![bug](https://user-images.githubusercontent.com/40413749/41662391-4fe5b13c-74a1-11e8-87bf-475378bdf12c.jpg)

cant select or play any game modes currently...
going to test with previous release
----

ok,great...modcomponent 2.1.1 is working for me it seems
im using a GOG version of the game by the way.

once again,thanks for your mods! the disabled chromatic abberation looks much better for me!

**Comment by WulfMarius** [comment]
Looks like GOG is still on TLD V1.29 (top left in your screenshot)
The latest release of ModComponent is for TLD V1.33 (and later), so ModComponent 2.1.1 is the proper version for you.

You should update when you get a newer version of TLD.

**Comment by ShabbirSS** [comment]
ah ok thanks, sorry mate,my phone was reset, i forgot i posted here xD cheers
