### ISSUE TITLE
1.34 Hotfix Issues

### ISSUE THREAD

**Issue by gambolingcat** [WulfMarius/ModComponent#5]
Looks like something in the 1.34 hotfix isn't playing nicely with Mod Component 2.2.1. Disabled all mods reliant on MC to rule them out, but with MC itself, getting two issues: 1. infinite inescapable "mapping" screen upon use of charcoal, and 2. can't initiate the climbing action on ropes. I'm guessing this has something to do with time-passing actions, but strangely, deploying/collecting ropes seems to work fine.

Thanks, Wulf.

**Comment by WulfMarius** [comment]
Yes, V1.34 introduced a subtle change that broke ModComponent.  
V2.2.2 is released and fixes this problem.

Thanks for reporting
