### ISSUE TITLE
ModRifelComponente

### ISSUE THREAD

**Issue by nbakulev** [WulfMarius/ModComponent#7]
Do you have an example for rifle component?
I  tried to use it, but had an error while loading games. Othe components works fine.

Initialize engine version: 2017.2.3p3 (726d0db4eeac)
GfxDevice: creating device client; threaded=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: AMD Radeon HD 6770M (ID=0x6740)
    Vendor:   ATI
    VRAM:     2292 MB
    Driver:   9.2.0.0
Begin MonoManager ReloadAssembly
- Completed reload, in  0.193 seconds
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 2.335437 ms
Loading Harmony...
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Loading mod loader...
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

 === This game is MODDED. Do not report any issues to Hinterland! === 
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Loading mod assemblies
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Applying Harmony patches
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Calling OnLoad methods
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[AssetLoader]: Version 2.1.0.0
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[ModComponentMapper]: Version 2.4.0.0
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[ModComponentMapper] Loading files from 'C:\Program Files (x86)\Steam\steamapps\common\TheLongDark\mods\auto-mapped' ...
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[AssetLoader]: Loading AssetBundle from 'C:\Program Files (x86)\Steam\steamapps\common\TheLongDark\mods\auto-mapped\Revolver\revolver.unity3d'.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[AssetLoader]: Processing asset 'Localization' as localization.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[AssetLoader]: Registered AssetBundle 'auto-mapped\Revolver\revolver.unity3d' with the following assets
  inventorygridicons/ico_gearitem__rubberduck => assets/inventorygridicons/ico_gearitem__rubberduck.png
  prefabs/equipedprefab => assets/prefabs/equipedprefab.prefab
  gear_revolver => assets/prefabs/gear_revolver.prefab
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

D3D shader blob is empty!
 
(Filename:  Line: 57)

Corrupt shader bytecode, couldn't decode 0 bytes
Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

D3D shader blob is empty!
 
(Filename:  Line: 57)

Corrupt shader bytecode, couldn't decode 0 bytes
Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

D3D shader blob is empty!
 
(Filename:  Line: 57)

Corrupt shader bytecode, couldn't decode 0 bytes
Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

D3D shader blob is empty!
 
(Filename:  Line: 57)

Corrupt shader bytecode, couldn't decode 0 bytes
Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

D3D shader blob is empty!
 
(Filename:  Line: 57)

Corrupt shader bytecode, couldn't decode 0 bytes
Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

D3D shader blob is empty!
 
(Filename:  Line: 57)

Corrupt shader bytecode, couldn't decode 0 bytes
Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

D3D shader blob is empty!
 
(Filename:  Line: 57)

Corrupt shader bytecode, couldn't decode 0 bytes
Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

D3D shader blob is empty!
 
(Filename:  Line: 57)

Corrupt shader bytecode, couldn't decode 0 bytes
Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

D3D shader blob is empty!
 
(Filename:  Line: 57)

Corrupt shader bytecode, couldn't decode 0 bytes
Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

D3D shader blob is empty!
 
(Filename:  Line: 57)

Corrupt shader bytecode, couldn't decode 0 bytes
Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

D3D shader blob is empty!
 
(Filename:  Line: 57)

Corrupt shader bytecode, couldn't decode 0 bytes
Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

D3D shader blob is empty!
 
(Filename:  Line: 57)

Corrupt shader bytecode, couldn't decode 0 bytes
Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

D3D shader blob is empty!
 
(Filename:  Line: 57)

Corrupt shader bytecode, couldn't decode 0 bytes
Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

D3D shader blob is empty!
 
(Filename:  Line: 57)

Corrupt shader bytecode, couldn't decode 0 bytes
Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

D3D shader blob is empty!
 
(Filename:  Line: 57)

Corrupt shader bytecode, couldn't decode 0 bytes
Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

D3D shader blob is empty!
 
(Filename:  Line: 57)

Corrupt shader bytecode, couldn't decode 0 bytes
Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

D3D shader blob is empty!
 
(Filename:  Line: 57)

Corrupt shader bytecode, couldn't decode 0 bytes
Failed to load GpuProgram from binary shader data in 'Standard'.
 
(Filename:  Line: 545)

D3D shader blob is empty!
 
(Filename:  Line: 57)

Corrupt shader bytecode, couldn't decode 0 bytes
WARNING: Shader Unsupported: 'Standard' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'Standard' - Pass 'META' has no vertex shader
D3D shader blob is empty!
 
(Filename:  Line: 57)

Corrupt shader bytecode, couldn't decode 0 bytes
D3D shader blob is empty!
 
(Filename:  Line: 57)

Corrupt shader bytecode, couldn't decode 0 bytes
[ModComponentMapper] Mapping EquipedPrefab
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

OnLoad method failed for type ModComponentMapper.Implementation of mod ModComponentMapper
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

NullReferenceException: Object reference not set to an instance of an object
  at FirstPersonItem.Awake () [0x00000] in <filename unknown>:0 
  at ModComponentMapper.Mapper.ConfiguredRifleFirstPersonItem (ModComponentAPI.ModRifleComponent modRifleComponent) [0x00000] in <filename unknown>:0 
  at ModComponentMapper.Mapper.ConfigureRifle (ModComponentAPI.ModComponent modComponent) [0x00000] in <filename unknown>:0 
  at ModComponentMapper.Mapper.Map (UnityEngine.GameObject prefab) [0x00000] in <filename unknown>:0 
  at ModComponentMapper.AutoMapper.MapModComponent (UnityEngine.GameObject prefab) [0x00000] in <filename unknown>:0 
  at ModComponentMapper.AutoMapper.AutoMapPrefab (System.String prefabName, System.String assetBundlePath) [0x00000] in <filename unknown>:0 
  at ModComponentMapper.AutoMapper.LoadAssetBundle (System.String relativePath) [0x00000] in <filename unknown>:0 
  at ModComponentMapper.AutoMapper.AutoMapDirectory (System.String directory, System.String modDirectory) [0x00000] in <filename unknown>:0 
  at ModComponentMapper.AutoMapper.AutoMapDirectory (System.String directory, System.String modDirectory) [0x00000] in <filename unknown>:0 
  at ModComponentMapper.AutoMapper.Initialize () [0x00000] in <filename unknown>:0 
  at ModComponentMapper.Implementation.OnLoad () [0x00000] in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <filename unknown>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
ModLoader.ModLoader:CallOnLoadMethods(List`1)
ModLoader.ModLoader:Start()
System.Reflection.MonoMethod:InternalInvoke(Object, Object[], Exception&)
System.Reflection.MonoMethod:Invoke(Object, BindingFlags, Binder, Object[], CultureInfo)
System.Reflection.MethodBase:Invoke(Object, Object[])
Rewired.InputManager_Base:Awake()
UnityEngine.Object:INTERNAL_CALL_Internal_InstantiateSingle(Object, Vector3&, Quaternion&)
UnityEngine.Object:Internal_InstantiateSingle(Object, Vector3, Quaternion)
UnityEngine.Object:Instantiate(Object, Vector3, Quaternion)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
GameManager:InstantiateInputSystem()
BootUpdate:InitializeSystems()
BootUpdate:Awake()
 
(Filename:  Line: -1)

Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/TheLongDark/tld_Data/Mono/data-144CCF80.dll
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/TheLongDark/tld_Data/Mono/data-1442BE08.dll
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/TheLongDark/tld_Data/Mono/data-1DF50020.dll
Searching for compatible XInput library...
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/TheLongDark/tld_Data/Mono/xinput1_4.dll
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/TheLongDark/tld_Data/Mono/.\xinput1_4.dll
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/TheLongDark/tld_Data/Mono/xinput1_4.dll
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/TheLongDark/tld_Data/Mono/xinput1_4
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/TheLongDark/tld_Data/Mono/.\xinput1_4
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/TheLongDark/tld_Data/Mono/xinput1_4
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/TheLongDark/tld_Data/Mono/libxinput1_4.dll
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/TheLongDark/tld_Data/Mono/.\libxinput1_4.dll
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/TheLongDark/tld_Data/Mono/libxinput1_4.dll
Found Xinput1_3.dll.
Rewired found 0 joysticks attached.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

PlayerId = 0 is assigned 0 joysticks.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

WwiseUnity: Initialize sound engine ...
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

WwiseUnity: Sound engine initialized.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

[AssetLoader]: Registering pending sound banks.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Mods detected -- Crash reports disabled.
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Received stats and achievements from Steam

 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Unloading 6 Unused Serialized files (Serialized files now loaded: 1)
UnloadTime: 8.102567 ms
Profiler is not supported in this build
 
(Filename:  Line: 102)

-- SystemInfo --
deviceType: Desktop
processorType: Intel(R) Core(TM) i5-2500S CPU @ 2.70GHz
processorCount: 4
systemMemorySize: 16359 Mb
operatingSystem: Windows 7 Service Pack 1 (6.1.7601) 64bit
graphicsDeviceID: 0x6740
graphicsDeviceName: AMD Radeon HD 6770M
graphicsDeviceType: Direct3D11
graphicsDeviceVendor: ATI
graphicsDeviceVendorID: 0x1002
graphicsDeviceVersion: Direct3D 11.0 [level 11.0]
graphicsMemorySize: 2292 Mb
graphicsShaderLevel: 50
supportsShadows: True

 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Adding Gear category
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

GAME VERSION: Modded 1.37 39488 () Release 
 
(Filename: C:\buildslave\unity\build\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Shader 'Shader Forge/TLD_StandardObjMove': fallback shader 'LegacyIlluminShaderGUI' not found

Unloading 26352 unused Assets to reduce memory usage. Loaded Objects now: 81938.
Total: 299.938687 ms (FindLiveObjects: 8.371690 ms CreateObjectMapping: 12.357213 ms MarkObjects: 261.529414 ms  DeleteObjects: 17.679227 ms)

Setting up 2 worker threads for Enlighten.
  Thread -> id: d20 -> priority: 1 
  Thread -> id: ad0 -> priority: 1

**Comment by WulfMarius** [comment]
Some guy asked me to do it, but then shortly before it was done, disappeared and never talked to me again.   It's been sitting there for quite some time now and apparently doesn't work with the current version of TLD.
